# Use the official Python base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file first for caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Run the application as a non-root user
RUN useradd -m myuser
USER myuser

WORKDIR /app/src

# Run the application
ENTRYPOINT ["python", "__main__.py"]