version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
#  ors:
#    container_name: ors-app
#    ports:
#      - "8080:8080"
#      - "9001:9001"
#    image: openrouteservice/openrouteservice:nightly
#    user: "${UID:-0}:${GID:-0}"
#    volumes:
#      - ./docker/graphs:/home/ors/ors-core/data/graphs
#      - ./docker/elevation_cache:/home/ors/ors-core/data/elevation_cache
#      - ./docker/logs/ors:/home/ors/logs
#      - ./docker/logs/tomcat:/home/ors/tomcat/logs
#      - ./docker/conf:/home/ors/ors-conf
#      - ./docker/data:/home/ors/ors-core/data
#    environment:
#      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
#      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
#      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
#      - ORS_CONFIG=/home/ors/ors-conf/ors-config.yml
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "MONGO_URL=mongodb://mongo:27017/db"
      - "OPEN_ROUTE_SERVICE_URL=https://api.openrouteservice.org/v2/directions"
#      - "OPEN_ROUTE_SERVICE_API_KEY=yor_key"
      - "RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongo
  worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    environment:
      - "MONGO_URL=mongodb://mongo:27017/db"
      - "RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
      - fastapi
